# Generated by Django 5.1.6 on 2025-02-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistaprevia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Tamaños',
            field=models.CharField(blank=True, choices=[('1K', '1K'), ('1_5L', '1,5L'), ('2_5', '2,5'), ('3L', '3L'), ('500g', '500g'), ('900g', '900g'), ('120g', '120g')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Zero', 'Zero'), ('Clasica', 'Clasica'), ('Pomelo', 'Pomelo'), ('Manzana', 'Manzana'), ('Naranja', 'Naranja')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
