# Generated by Django 5.1.6 on 2025-02-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistaprevia', '0002_producto_tamaños_producto_tipo_alter_producto_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Tamaños',
            new_name='tamaños',
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
