# Generated by Django 5.1.6 on 2025-05-03 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/%Y/%m/%d/')),
                ('tipo', models.CharField(blank=True, choices=[('Zero', 'Zero'), ('Clasica', 'Clasica'), ('Pomelo', 'Pomelo'), ('Manzana', 'Manzana'), ('Naranja', 'Naranja')], max_length=100, null=True)),
                ('tamaños', models.CharField(blank=True, choices=[('1K', '1K'), ('1_5L', '1,5L'), ('2_5', '2,5'), ('3L', '3L'), ('500g', '500g'), ('900g', '900g'), ('120g', '120g')], max_length=100, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.marca')),
            ],
        ),
    ]
