# Generated by Django 5.1.6 on 2025-05-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Zero', 'Zero'), ('Clasica', 'Clasica'), ('Pomelo', 'Pomelo'), ('Manzana', 'Manzana'), ('Limón', 'Limón'), ('Pera', 'Pera'), ('Uva', 'Uva'), ('Naranja', 'Naranja')], max_length=100, null=True),
        ),
    ]
