# Generated by Django 5.1.6 on 2025-06-12 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_sub_categoria_producto_sub_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='sub_categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Zero', 'Zero'), ('Clasica', 'Clasica'), ('Pomelo', 'Pomelo'), ('Manzana', 'Manzana'), ('Limón', 'Limón'), ('Pera', 'Pera'), ('Uva', 'Uva'), ('Naranja', 'Naranja'), ('Durazno', 'Durazno'), ('Frutilla', 'Frutilla'), ('Tirabuzón', 'Tirabuzón'), ('Limonada', 'Limonada'), ('Tónica', 'Tónica'), ('Spaghetti', 'Spaghetti'), ('Moño', 'Moño'), ('Fusilli', 'Fusilli'), ('Codito', 'Codito'), ('Cinta', 'Cinta'), ('Fetuccine', 'Fettuccine'), ('Mostacchioli', 'Mostaccioli'), ('Dadito', 'Dadito'), ('Caracol', 'Caracol'), ('Integral', 'Integral'), ('Fino', 'Fino'), ('Largo', 'Largo')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='productos.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.subcategoria'),
        ),
        migrations.DeleteModel(
            name='Sub_categoria',
        ),
    ]
